using SperoFlow.Domain;

namespace SperoFlow.Domain.Tests;

public sealed class NonNegotiableRulesTests
{
    // --- Rule 1: Browser clients never choose a proposal owner or call a private AI service ---

    [Fact]
    public void Rule1_AuditableEntity_Rejects_Empty_OwnerId()
    {
        Assert.Throws<DomainValidationException>(() => new TaskItem(
            Guid.Empty,
            "Unauthorized Task",
            null,
            LifeArea.Work));

        Assert.Throws<DomainValidationException>(() => new LifeRole(
            Guid.Empty,
            "Unauthorized Role",
            LifeRoleCategory.External,
            LifeArea.Work,
            "#000000",
            "person"));

        Assert.Throws<DomainValidationException>(() => new AiActionProposal(
            Guid.Empty,
            AiProposalKind.CreateTask,
            "client",
            "source-key",
            "Title",
            "Description",
            "{\"title\":\"Title\"}"));
    }

    // --- Rule 2: AI services never write the primary application database directly ---

    [Fact]
    public void Rule2_AI_Proposals_Remain_Pending_Until_User_Approve()
    {
        var ownerId = Guid.CreateVersion7();
        var proposal = new AiActionProposal(
            ownerId,
            AiProposalKind.CreateTask,
            "ai-service",
            "ai-service:job:1001",
            "AI Recommended Task",
            "This task was generated by AI.",
            "{\"title\":\"AI Recommended Task\",\"lifeArea\":\"Work\"}");

        // Proposal is created in Pending state without mutating any primary application entity
        Assert.Equal(AiProposalState.Pending, proposal.State);
        Assert.Null(proposal.AppliedEntityId);
        Assert.Null(proposal.ResolvedAt);
    }

    // --- Rule 3: Every proposal is owner-scoped, concurrency-protected, audited, and requires explicit approval ---

    [Fact]
    public void Rule3_Every_Proposal_Enforces_Owner_Scoping_And_Concurrency_Token()
    {
        var ownerId = Guid.CreateVersion7();
        var proposal = new AiActionProposal(
            ownerId,
            AiProposalKind.CreateHabit,
            "habit-agent",
            "habit:1",
            "Daily Hydration",
            "Track daily hydration.",
            "{\"title\":\"Daily Hydration\"}");

        Assert.Equal(ownerId, proposal.OwnerId);
        Assert.NotEqual(Guid.Empty, proposal.ConcurrencyToken);

        var originalToken = proposal.ConcurrencyToken;
        var habitId = Guid.CreateVersion7();
        proposal.Approve(habitId);

        // Concurrency token is rotated upon state change
        Assert.NotEqual(originalToken, proposal.ConcurrencyToken);
        Assert.Equal(habitId, proposal.AppliedEntityId);
    }

    // --- Rule 4: Proposals are applied only after ASP.NET re-validates payload, ownership, and target state ---

    [Fact]
    public void Rule4_Approve_Requires_Valid_Applied_Entity_Id()
    {
        var ownerId = Guid.CreateVersion7();
        var proposal = new AiActionProposal(
            ownerId,
            AiProposalKind.CreateTask,
            "scheduler",
            "sched:1",
            "Schedule Task",
            "Proposed time block",
            "{\"title\":\"Schedule Task\"}");

        Assert.Throws<DomainValidationException>(() => proposal.Approve(Guid.Empty));
    }

    [Fact]
    public void Rule4_Mismatched_Source_Concurrency_Token_Fails_Validation()
    {
        var ownerId = Guid.CreateVersion7();
        var journalEntryId = Guid.CreateVersion7();

        // Insight requires valid source concurrency token
        Assert.Throws<DomainValidationException>(() => new JournalInsight(
            ownerId,
            journalEntryId,
            Guid.Empty, // Missing revision token
            "protected-payload"));

        Assert.Throws<DomainValidationException>(() => new GoalRoadmapProposal(
            ownerId,
            Guid.CreateVersion7(),
            Guid.CreateVersion7(),
            Guid.Empty, // Missing revision token
            "protected-payload"));
    }

    // --- Rule 5: Agents return plans/recommendations, never unreviewed mutations ---

    [Fact]
    public void Rule5_Creating_Proposal_Does_Not_Mutate_Target_Entity()
    {
        var ownerId = Guid.CreateVersion7();
        var task = new TaskItem(
            ownerId,
            "Original Unmutated Title",
            "Original Description",
            LifeArea.Work,
            EisenhowerQuadrant.Unsorted);

        var initialToken = task.ConcurrencyToken;
        var initialQuadrant = task.Quadrant;
        var initialStartAt = task.StartAt;

        // Simulate AI returning a proposal plan
        _ = new AiActionProposal(
            ownerId,
            AiProposalKind.ApplyTaskClassification,
            "eisenhower-agent",
            "eisenhower:" + task.Id.ToString("N"),
            "Classify Task",
            "Recommending Q2 classification.",
            "{\"taskId\":\"" + task.Id + "\",\"quadrant\":\"Q2\"}");

        // Target task remains completely unchanged
        Assert.Equal(initialToken, task.ConcurrencyToken);
        Assert.Equal(initialQuadrant, task.Quadrant);
        Assert.Equal(initialStartAt, task.StartAt);
    }
}
